### ISSUE TITLE
Tie Game

### ISSUE THREAD

**Issue by codemonkeyrawks** [jlu5/eggdrop-color-uno#3]
When the game ends and a player plays ex: blue 1 then the other player looses but has a red 1 is this not considered a tie game?

**Comment by jlu5** [comment]
I've never heard of that rule!

In any case, this repository was originally only listed for completeness, and I never planned to be actively maintaining this code... Upstream has not updated it for almost a decade now.

I want to leave this note for reference and properly archive the repo soon.

**Comment by codemonkeyrawks** [comment]
I think I will self resolve this issue: looking at the official rules the game is correct. I can look to code myself if I need a tie game part.

Thanks!
